name: Ubuntu x86_64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update package list
      run: sudo apt-get update

    - name: Installing Toolchain
      run: sudo apt-get install -y gcc

    - name: Installing Dependencies
      run: sudo apt-get install -y libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libminiupnpc-dev libopenmpt-dev

    - name: Build SRB2
      run: make -C src/ --keep-going LINUX64=1 SDL=1 -j3

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: srb2legacyadds
        path: |
          bin/
          src/comptime.h

    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: srb2legacyadds
      continue-on-error: true
