name: Windows x86

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC:  i686-w64-mingw32-gcc 
  WINDRES: i686-w64-mingw32-windres

jobs:
   build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4

     - name: Update package list
       run: sudo apt-get update 

     - name: Installing Toolchain
       run: sudo apt-get install -y gcc-mingw64-w64 binutils-mingw-w64-i686 

     - name: Build SRB2
       run: make -C src/ --keep-going MINGW=1 SDL=1 -j3 

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.3.4
       with:
        name: srb2legacyadds-WIN32
        path: |
          bin/
          src/comptime.h 

     - name: Download Artifacts
       uses: actions/download-artifact@v4.1.8
       with:
        name: srb2legacyadds-WIN32
       continue-on-error: true

