name: Windows x86_64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC: gcc
  
defaults:
    run:
      shell: msys2 {0}

jobs:
   build:
    runs-on: windows-latest
    steps: 
     - uses: actions/checkout@v4  
     - name: Setup Environment
       uses: msys2/setup-msys2@v2
       with:
        install: >- 
         git 
         make
         mingw-w64-x86_64-gcc 
         nasm



     
     - name: Build SRB2
       run: make -C src/ --keep-going MINGW64=1 SDL=1 -j3 

   
     - uses: actions/upload-artifact@v4.3.4
       with:
        name: srb2legacyadds-WIN64
        path: |
          bin/
          src/comptime.h 

  
     - uses: actions/download-artifact@v4.1.8
       with:
        name: srb2legacyadds-WIN64
       continue-on-error: true