name: Windows x86_64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC:  x86_64-w64-mingw32-gcc-win32
  WINDRES: x86_64-w64-mingw32-windres

jobs:
   build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4

     - name: Update package list
       run: sudo apt-get update 

     - name: Installing Toolchain
       run: sudo apt-get install -y mingw-w64 binutils-mingw-w64 nasm 

     - name: Build SRB2
       run: make -C src/ --keep-going MINGW64=1 SDL=1 -j3 

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.3.4
       with:
        name: srb2legacyadds-WIN64
        path: |
          bin/
          src/comptime.h 

     - name: Download Artifacts
       uses: actions/download-artifact@v4.1.8
       with:
        name: srb2legacyadds-WIN64
       continue-on-error: true

